package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AreasAtuacao generated by hbm2java
 */
@Entity
@Table(name="areas_atuacao"
    ,schema="public"
)
@SequenceGenerator(name = "areasatuacao_seq", sequenceName = "areasatuacao_seq", allocationSize = 1)
public class AreasAtuacao  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set<Experiencias> experienciases = new HashSet<Experiencias>(0);

    public AreasAtuacao() {
    }

	
    public AreasAtuacao(int id) {
        this.id = id;
    }
    public AreasAtuacao(int id, String nome, Set<Experiencias> experienciases) {
       this.id = id;
       this.nome = nome;
       this.experienciases = experienciases;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "areasatuacao_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", length=200)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areasAtuacao")
    public Set<Experiencias> getExperienciases() {
        return this.experienciases;
    }
    
    public void setExperienciases(Set<Experiencias> experienciases) {
        this.experienciases = experienciases;
    }




}


