package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Atestados generated by hbm2java
 */
@Entity
@Table(name="atestados"
    ,schema="public"
)
@SequenceGenerator(name = "atestados_seq", sequenceName = "atestados_seq", allocationSize = 1)
public class Atestados  implements java.io.Serializable {


     private int id;
     private Funcionarios funcionarios;
     private Date dataInicio;
     private Date dataFim;
     private String medico;
     private String observacoes;

    public Atestados() {
    }

	
    public Atestados(int id, Funcionarios funcionarios) {
        this.id = id;
        this.funcionarios = funcionarios;
    }
    public Atestados(int id, Funcionarios funcionarios, Date dataInicio, Date dataFim, String medico, String observacoes) {
       this.id = id;
       this.funcionarios = funcionarios;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
       this.medico = medico;
       this.observacoes = observacoes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "atestados_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionarios_id", nullable=false)
    public Funcionarios getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_inicio", length=22)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_fim", length=22)
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    
    @Column(name="medico", length=45)
    public String getMedico() {
        return this.medico;
    }
    
    public void setMedico(String medico) {
        this.medico = medico;
    }

    
    @Column(name="observacoes", length=500)
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }




}


