package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calculos generated by hbm2java
 */
@Entity
@Table(name = "calculos", schema = "public")
@SequenceGenerator(name = "calculos_seq", sequenceName = "calculos_seq", allocationSize = 1)
public class Calculos implements java.io.Serializable {

    private int id;
    private Eventos eventos;
    private Funcionarios funcionarios;
    private Double valor;
    private Double referencia;
    private Date perIncial;
    private Date perFinal;
    private Date dataCalculo;
    private Boolean perFechado;
    private Date dataPagamento;

    public Calculos() {
    }

    public Calculos(int id, Eventos eventos, Funcionarios funcionarios) {
        this.id = id;
        this.eventos = eventos;
        this.funcionarios = funcionarios;
    }

    public Calculos(int id, Eventos eventos, Funcionarios funcionarios, Double valor, Double referencia, Date perIncial,
            Date perFinal, Date dataCalculo, Boolean perFechado, Date dataPagamento) {
        this.id = id;
        this.eventos = eventos;
        this.funcionarios = funcionarios;
        this.valor = valor;
        this.referencia = referencia;
        this.perIncial = perIncial;
        this.perFinal = perFinal;
        this.dataCalculo = dataCalculo;
        this.perFechado = perFechado;
        this.dataPagamento = dataPagamento;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "calculos_seq")
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "eventos_id", nullable = false)
    public Eventos getEventos() {
        return this.eventos;
    }

    public void setEventos(Eventos eventos) {
        this.eventos = eventos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "funcionarios_id", nullable = false)
    public Funcionarios getFuncionarios() {
        return this.funcionarios;
    }

    public void setFuncionarios(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }

    @Column(name = "valor", precision = 17, scale = 17)
    public Double getValor() {
        return this.valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    @Column(name = "referencia", precision = 17, scale = 17)
    public Double getReferencia() {
        return this.referencia;
    }

    public void setReferencia(Double referencia) {
        this.referencia = referencia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "per_incial", length = 22)
    public Date getPerIncial() {
        return this.perIncial;
    }

    public void setPerIncial(Date perIncial) {
        this.perIncial = perIncial;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "per_final", length = 22)
    public Date getPerFinal() {
        return this.perFinal;
    }

    public void setPerFinal(Date perFinal) {
        this.perFinal = perFinal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data_calculo", length = 22)
    public Date getDataCalculo() {
        return this.dataCalculo;
    }

    public void setDataCalculo(Date dataCalculo) {
        this.dataCalculo = dataCalculo;
    }

    @Column(name = "per_fechado")
    public Boolean isPerFechado() {
        return this.perFechado;
    }

    public void setPerFechado(Boolean perFechado) {
        this.perFechado = perFechado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data_pagamento", length = 22)
    public Date getDataPagamento() {
        return this.dataPagamento;
    }

    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }

}
