package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargos generated by hbm2java
 */
@Entity
@Table(name="cargos"
    ,schema="public"
)
@SequenceGenerator(name = "cargos_seq", sequenceName = "cargos_seq", allocationSize = 1)
public class Cargos  implements java.io.Serializable {


     private int id;
     private Cbo cbo;
     private Setores setores;
     private String nome;
     private String atribuicoes;
     private Set<Vagas> vagases = new HashSet<Vagas>(0);
     private Set<FuncionariosCargos> funcionariosCargoses = new HashSet<FuncionariosCargos>(0);

    public Cargos() {
    }

	
    public Cargos(int id, Cbo cbo, Setores setores) {
        this.id = id;
        this.cbo = cbo;
        this.setores = setores;
    }
    public Cargos(int id, Cbo cbo, Setores setores, String nome, String atribuicoes, Set<Vagas> vagases, Set<FuncionariosCargos> funcionariosCargoses) {
       this.id = id;
       this.cbo = cbo;
       this.setores = setores;
       this.nome = nome;
       this.atribuicoes = atribuicoes;
       this.vagases = vagases;
       this.funcionariosCargoses = funcionariosCargoses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cargos_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cbo_id", nullable=false)
    public Cbo getCbo() {
        return this.cbo;
    }
    
    public void setCbo(Cbo cbo) {
        this.cbo = cbo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="setores_id", nullable=false)
    public Setores getSetores() {
        return this.setores;
    }
    
    public void setSetores(Setores setores) {
        this.setores = setores;
    }

    
    @Column(name="nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="atribuicoes", length=1000)
    public String getAtribuicoes() {
        return this.atribuicoes;
    }
    
    public void setAtribuicoes(String atribuicoes) {
        this.atribuicoes = atribuicoes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargos")
    public Set<Vagas> getVagases() {
        return this.vagases;
    }
    
    public void setVagases(Set<Vagas> vagases) {
        this.vagases = vagases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargos")
    public Set<FuncionariosCargos> getFuncionariosCargoses() {
        return this.funcionariosCargoses;
    }
    
    public void setFuncionariosCargoses(Set<FuncionariosCargos> funcionariosCargoses) {
        this.funcionariosCargoses = funcionariosCargoses;
    }




}


