package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidades generated by hbm2java
 */
@Entity
@Table(name="cidades"
    ,schema="public"
)
@SequenceGenerator(name = "cidades_seq", sequenceName = "cidades_seq", allocationSize = 1)
public class Cidades  implements java.io.Serializable {


     private int id;
     private String uf;
     private String nome;
     private Set<Enderecos> enderecoses = new HashSet<Enderecos>(0);

    public Cidades() {
    }

	
    public Cidades(int id) {
        this.id = id;
    }
    public Cidades(int id, String uf, String nome, Set<Enderecos> enderecoses) {
       this.id = id;
       this.uf = uf;
       this.nome = nome;
       this.enderecoses = enderecoses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cidades_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="uf", length=45)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="nome", length=200)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidades")
    public Set<Enderecos> getEnderecoses() {
        return this.enderecoses;
    }
    
    public void setEnderecoses(Set<Enderecos> enderecoses) {
        this.enderecoses = enderecoses;
    }




}


