package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dependentes generated by hbm2java
 */
@Entity
@Table(name="dependentes"
    ,schema="public"
)
@SequenceGenerator(name = "dependentes_seq", sequenceName = "dependentes_seq", allocationSize = 1)
public class Dependentes  implements java.io.Serializable {


     private int id;
     private Funcionarios funcionarios;
     private Date dataNascimento;
     private String cpf;
     private String certidaoNascimento;
     private Character impostoRenda;
     private Character auxilioCreche;
     private Character salarioFamilia;
     private String nome;

    public Dependentes() {
    }

	
    public Dependentes(int id, Funcionarios funcionarios) {
        this.id = id;
        this.funcionarios = funcionarios;
    }
    public Dependentes(int id, Funcionarios funcionarios, Date dataNascimento, String cpf, String certidaoNascimento, Character impostoRenda, Character auxilioCreche, Character salarioFamilia, String nome) {
       this.id = id;
       this.funcionarios = funcionarios;
       this.dataNascimento = dataNascimento;
       this.cpf = cpf;
       this.certidaoNascimento = certidaoNascimento;
       this.impostoRenda = impostoRenda;
       this.auxilioCreche = auxilioCreche;
       this.salarioFamilia = salarioFamilia;
       this.nome = nome;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "dependentes_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionarios_id", nullable=false)
    public Funcionarios getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_nascimento", length=22)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="cpf", length=11)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="certidao_nascimento", length=45)
    public String getCertidaoNascimento() {
        return this.certidaoNascimento;
    }
    
    public void setCertidaoNascimento(String certidaoNascimento) {
        this.certidaoNascimento = certidaoNascimento;
    }

    
    @Column(name="imposto_renda", length=1)
    public Character getImpostoRenda() {
        return this.impostoRenda;
    }
    
    public void setImpostoRenda(Character impostoRenda) {
        this.impostoRenda = impostoRenda;
    }

    
    @Column(name="auxilio_creche", length=1)
    public Character getAuxilioCreche() {
        return this.auxilioCreche;
    }
    
    public void setAuxilioCreche(Character auxilioCreche) {
        this.auxilioCreche = auxilioCreche;
    }

    
    @Column(name="salario_familia", length=1)
    public Character getSalarioFamilia() {
        return this.salarioFamilia;
    }
    
    public void setSalarioFamilia(Character salarioFamilia) {
        this.salarioFamilia = salarioFamilia;
    }

    
    @Column(name="nome", length=200)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


