package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Escolaridade generated by hbm2java
 */
@Entity
@Table(name="escolaridade"
    ,schema="public"
)
@SequenceGenerator(name = "escolaridade_seq", sequenceName = "escolaridade_seq", allocationSize = 1)
public class Escolaridade  implements java.io.Serializable {


     private int id;
     private String grau;
     private Set<Formacoes> formacoeses = new HashSet<Formacoes>(0);

    public Escolaridade() {
    }

	
    public Escolaridade(int id) {
        this.id = id;
    }
    public Escolaridade(int id, String grau, Set<Formacoes> formacoeses) {
       this.id = id;
       this.grau = grau;
       this.formacoeses = formacoeses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "escolaridade_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="grau", length=200)
    public String getGrau() {
        return this.grau;
    }
    
    public void setGrau(String grau) {
        this.grau = grau;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="escolaridade")
    public Set<Formacoes> getFormacoeses() {
        return this.formacoeses;
    }
    
    public void setFormacoeses(Set<Formacoes> formacoeses) {
        this.formacoeses = formacoeses;
    }




}


