package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstCivil generated by hbm2java
 */
@Entity
@Table(name="est_civil"
    ,schema="public"
)
@SequenceGenerator(name = "estcivil_seq", sequenceName = "estcivil_seq", allocationSize = 1)
public class EstCivil  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set<Pessoas> pessoases = new HashSet<Pessoas>(0);

    public EstCivil() {
    }

	
    public EstCivil(int id) {
        this.id = id;
    }
    public EstCivil(int id, String descricao, Set<Pessoas> pessoases) {
       this.id = id;
       this.descricao = descricao;
       this.pessoases = pessoases;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "estcivil_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descricao", length=1000)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estCivil")
    public Set<Pessoas> getPessoases() {
        return this.pessoases;
    }
    
    public void setPessoases(Set<Pessoas> pessoases) {
        this.pessoases = pessoases;
    }




}


