package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Eventos generated by hbm2java
 */
@Entity
@Table(name="eventos"
    ,schema="public"
)
@SequenceGenerator(name = "eventos_seq", sequenceName = "eventos_seq", allocationSize = 1)
public class Eventos  implements java.io.Serializable {


     private int id;
     private GrupoEventos grupoEventos;
     private String descricao;
     private TipoEvento tipo;
     private String formula;
     private Short automatico;
     private Double referencia;
     private Double percentual;
     private Double valorMinimo;
     private Double valorMaximo;
     private Set<Eventos> incidencias;
     private Integer ordemCalculo;
     private Set<EveFixos> eveFixoses = new HashSet<EveFixos>(0);
     private Set<Calculos> calculoses = new HashSet<Calculos>(0);

    public Eventos() {
    }

	
    public Eventos(int id, GrupoEventos grupoEventos) {
        this.id = id;
        this.grupoEventos = grupoEventos;
    }
    public Eventos(int id, GrupoEventos grupoEventos, String descricao, TipoEvento tipo, String formula, Short automatico, Double referencia, Double percentual, Double valorMinimo, Double valorMaximo, Set<Eventos> incidencias, Integer ordemCalculo, Set<EveFixos> eveFixoses, Set<Calculos> calculoses) {
       this.id = id;
       this.grupoEventos = grupoEventos;
       this.descricao = descricao;
       this.tipo = tipo;
       this.formula = formula;
       this.automatico = automatico;
       this.referencia = referencia;
       this.percentual = percentual;
       this.valorMinimo = valorMinimo;
       this.valorMaximo = valorMaximo;
       this.incidencias = incidencias;
       this.ordemCalculo = ordemCalculo;
       this.eveFixoses = eveFixoses;
       this.calculoses = calculoses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "eventos_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grupo_eventos_id", nullable=false)
    public GrupoEventos getGrupoEventos() {
        return this.grupoEventos;
    }
    
    public void setGrupoEventos(GrupoEventos grupoEventos) {
        this.grupoEventos = grupoEventos;
    }

    
    @Column(name="descricao", length=1000)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="tipo")
    public TipoEvento getTipo() {
        return this.tipo;
    }
    
    public void setTipo(TipoEvento tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="formula", length=5000)
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }

    
    @Column(name="automatico")
    public Short getAutomatico() {
        return this.automatico;
    }
    
    public void setAutomatico(Short automatico) {
        this.automatico = automatico;
    }

    
    @Column(name="referencia", precision=17, scale=17)
    public Double getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(Double referencia) {
        this.referencia = referencia;
    }

    
    @Column(name="percentual", precision=17, scale=17)
    public Double getPercentual() {
        return this.percentual;
    }
    
    public void setPercentual(Double percentual) {
        this.percentual = percentual;
    }

    
    @Column(name="valor_minimo", precision=17, scale=17)
    public Double getValorMinimo() {
        return this.valorMinimo;
    }
    
    public void setValorMinimo(Double valorMinimo) {
        this.valorMinimo = valorMinimo;
    }

    
    @Column(name="valor_maximo", precision=17, scale=17)
    public Double getValorMaximo() {
        return this.valorMaximo;
    }
    
    public void setValorMaximo(Double valorMaximo) {
        this.valorMaximo = valorMaximo;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="eventos_incidencias", schema="public")
    public Set<Eventos> getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set<Eventos> incidencias) {
        this.incidencias = incidencias;
    }

    
    @Column(name="ordem_calculo")
    public Integer getOrdemCalculo() {
        return this.ordemCalculo;
    }
    
    public void setOrdemCalculo(Integer ordemCalculo) {
        this.ordemCalculo = ordemCalculo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="eventos")
    public Set<EveFixos> getEveFixoses() {
        return this.eveFixoses;
    }
    
    public void setEveFixoses(Set<EveFixos> eveFixoses) {
        this.eveFixoses = eveFixoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="eventos")
    public Set<Calculos> getCalculoses() {
        return this.calculoses;
    }
    
    public void setCalculoses(Set<Calculos> calculoses) {
        this.calculoses = calculoses;
    }




}


