package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Experiencias generated by hbm2java
 */
@Entity
@Table(name="experiencias"
    ,schema="public"
)
@SequenceGenerator(name = "experiencias_seq", sequenceName = "experiencias_seq", allocationSize = 1)
public class Experiencias  implements java.io.Serializable {


     private int id;
     private AreasAtuacao areasAtuacao;
     private Curriculos curriculos;
     private Date dataInicio;
     private Date dataFim;
     private String cargoOcupado;
     private String observacoes;

    public Experiencias() {
    }

	
    public Experiencias(int id, AreasAtuacao areasAtuacao, Curriculos curriculos) {
        this.id = id;
        this.areasAtuacao = areasAtuacao;
        this.curriculos = curriculos;
    }
    public Experiencias(int id, AreasAtuacao areasAtuacao, Curriculos curriculos, Date dataInicio, Date dataFim, String cargoOcupado, String observacoes) {
       this.id = id;
       this.areasAtuacao = areasAtuacao;
       this.curriculos = curriculos;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
       this.cargoOcupado = cargoOcupado;
       this.observacoes = observacoes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "experiencias_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="areas_atuacao_id", nullable=false)
    public AreasAtuacao getAreasAtuacao() {
        return this.areasAtuacao;
    }
    
    public void setAreasAtuacao(AreasAtuacao areasAtuacao) {
        this.areasAtuacao = areasAtuacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curriculos_id", nullable=false)
    public Curriculos getCurriculos() {
        return this.curriculos;
    }
    
    public void setCurriculos(Curriculos curriculos) {
        this.curriculos = curriculos;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_inicio", length=22)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_fim", length=22)
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    
    @Column(name="cargo_ocupado", length=100)
    public String getCargoOcupado() {
        return this.cargoOcupado;
    }
    
    public void setCargoOcupado(String cargoOcupado) {
        this.cargoOcupado = cargoOcupado;
    }

    
    @Column(name="observacoes", length=200)
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }




}


