package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Formacoes generated by hbm2java
 */
@Entity
@Table(name="formacoes"
    ,schema="public"
)
@SequenceGenerator(name = "formacoes_seq", sequenceName = "formacoes_seq", allocationSize = 1)
public class Formacoes  implements java.io.Serializable {


     private int id;
     private Curriculos curriculos;
     private Escolaridade escolaridade;
     private String instituicaoEnsino;
     private Date dataInicio;
     private Date dataFim;
     private String nome;

    public Formacoes() {
    }

	
    public Formacoes(int id, Curriculos curriculos, Escolaridade escolaridade) {
        this.id = id;
        this.curriculos = curriculos;
        this.escolaridade = escolaridade;
    }
    public Formacoes(int id, Curriculos curriculos, Escolaridade escolaridade, String instituicaoEnsino, Date dataInicio, Date dataFim, String nome) {
       this.id = id;
       this.curriculos = curriculos;
       this.escolaridade = escolaridade;
       this.instituicaoEnsino = instituicaoEnsino;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
       this.nome = nome;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "formacoes_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curriculos_id", nullable=false)
    public Curriculos getCurriculos() {
        return this.curriculos;
    }
    
    public void setCurriculos(Curriculos curriculos) {
        this.curriculos = curriculos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="escolaridade_id", nullable=false)
    public Escolaridade getEscolaridade() {
        return this.escolaridade;
    }
    
    public void setEscolaridade(Escolaridade escolaridade) {
        this.escolaridade = escolaridade;
    }

    
    @Column(name="instituicao_ensino", length=200)
    public String getInstituicaoEnsino() {
        return this.instituicaoEnsino;
    }
    
    public void setInstituicaoEnsino(String instituicaoEnsino) {
        this.instituicaoEnsino = instituicaoEnsino;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_inicio", length=22)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_fim", length=22)
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    
    @Column(name="nome", length=200)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


