package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionariosCargos generated by hbm2java
 */
@Entity
@Table(name="funcionarios_cargos"
    ,schema="public"
)
public class FuncionariosCargos  implements java.io.Serializable {


     private FuncionariosCargosId id;
     private Cargos cargos;
     private Funcionarios funcionarios;
     private Date dataInicio;

    public FuncionariosCargos() {
    }

	
    public FuncionariosCargos(FuncionariosCargosId id, Cargos cargos, Funcionarios funcionarios) {
        this.id = id;
        this.cargos = cargos;
        this.funcionarios = funcionarios;
    }
    public FuncionariosCargos(FuncionariosCargosId id, Cargos cargos, Funcionarios funcionarios, Date dataInicio) {
       this.id = id;
       this.cargos = cargos;
       this.funcionarios = funcionarios;
       this.dataInicio = dataInicio;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cargosId", column=@Column(name="cargos_id", nullable=false) ), 
        @AttributeOverride(name="funcionariosId", column=@Column(name="funcionarios_id", nullable=false) ) } )
    public FuncionariosCargosId getId() {
        return this.id;
    }
    
    public void setId(FuncionariosCargosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cargos_id", nullable=false, insertable=false, updatable=false)
    public Cargos getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Cargos cargos) {
        this.cargos = cargos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionarios_id", nullable=false, insertable=false, updatable=false)
    public Funcionarios getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_inicio", length=22)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }




}


