package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcionarios generated by hbm2java
 */
@Entity
@Table(name="funcionarios"
    ,schema="public"
)
@SequenceGenerator(name = "funcionarios_seq", sequenceName = "funcionarios_seq", allocationSize = 1)
public class Funcionarios  implements java.io.Serializable {


     private int id;
     private Pessoas pessoas;
     private Date dataAdmissao;
     private String nomePai;
     private String nomeMae;
     private String pis;
     private Date dataEmissaoPis;
     private String reservista;
     private String categoriaReservista;
     private String nacionalidade;
     private String naturalidade;
     private Character seguroDesemprego;
     private Date dataDemissao;
     private String numeroCarteiraTrabalho;
     private String serieCarteiraTrabalho;
     private String estadoCarteiraTrabalho;
     private Date dataEmissaoCarteiraTrabalho;
     private String cnh;
     private String categoriaCnh;
     private String orgaoEmissorCnh;
     private Date dataEmissaoCnh;
     private Date dataPrimeiraCnh;
     private Date dataValidadeCnh;
     private String tituloEleitor;
     private String zonaTituloEleitor;
     private String secaoTituloEleitor;
     private Set<EveFixos> eveFixoses = new HashSet<EveFixos>(0);
     private Set<Calculos> calculoses = new HashSet<Calculos>(0);
     private Set<Dependentes> dependenteses = new HashSet<Dependentes>(0);
     private Set<Atestados> atestadoses = new HashSet<Atestados>(0);
     private Set<Salarios> salarioses = new HashSet<Salarios>(0);
     private Set<FuncionariosCargos> funcionariosCargoses = new HashSet<FuncionariosCargos>(0);

    public Funcionarios() {
    }

	
    public Funcionarios(int id, Pessoas pessoas) {
        this.id = id;
        this.pessoas = pessoas;
    }
    public Funcionarios(int id, Pessoas pessoas, Date dataAdmissao, String nomePai, String nomeMae, String pis, Date dataEmissaoPis, String reservista, String categoriaReservista, String nacionalidade, String naturalidade, Character seguroDesemprego, Date dataDemissao, String numeroCarteiraTrabalho, String serieCarteiraTrabalho, String estadoCarteiraTrabalho, Date dataEmissaoCarteiraTrabalho, String cnh, String categoriaCnh, String orgaoEmissorCnh, Date dataEmissaoCnh, Date dataPrimeiraCnh, Date dataValidadeCnh, String tituloEleitor, String zonaTituloEleitor, String secaoTituloEleitor, Set<EveFixos> eveFixoses, Set<Calculos> calculoses, Set<Dependentes> dependenteses, Set<Atestados> atestadoses, Set<Salarios> salarioses, Set<FuncionariosCargos> funcionariosCargoses) {
       this.id = id;
       this.pessoas = pessoas;
       this.dataAdmissao = dataAdmissao;
       this.nomePai = nomePai;
       this.nomeMae = nomeMae;
       this.pis = pis;
       this.dataEmissaoPis = dataEmissaoPis;
       this.reservista = reservista;
       this.categoriaReservista = categoriaReservista;
       this.nacionalidade = nacionalidade;
       this.naturalidade = naturalidade;
       this.seguroDesemprego = seguroDesemprego;
       this.dataDemissao = dataDemissao;
       this.numeroCarteiraTrabalho = numeroCarteiraTrabalho;
       this.serieCarteiraTrabalho = serieCarteiraTrabalho;
       this.estadoCarteiraTrabalho = estadoCarteiraTrabalho;
       this.dataEmissaoCarteiraTrabalho = dataEmissaoCarteiraTrabalho;
       this.cnh = cnh;
       this.categoriaCnh = categoriaCnh;
       this.orgaoEmissorCnh = orgaoEmissorCnh;
       this.dataEmissaoCnh = dataEmissaoCnh;
       this.dataPrimeiraCnh = dataPrimeiraCnh;
       this.dataValidadeCnh = dataValidadeCnh;
       this.tituloEleitor = tituloEleitor;
       this.zonaTituloEleitor = zonaTituloEleitor;
       this.secaoTituloEleitor = secaoTituloEleitor;
       this.eveFixoses = eveFixoses;
       this.calculoses = calculoses;
       this.dependenteses = dependenteses;
       this.atestadoses = atestadoses;
       this.salarioses = salarioses;
       this.funcionariosCargoses = funcionariosCargoses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "funcionarios_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoas_id", nullable=false)
    public Pessoas getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Pessoas pessoas) {
        this.pessoas = pessoas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_admissao", length=13)
    public Date getDataAdmissao() {
        return this.dataAdmissao;
    }
    
    public void setDataAdmissao(Date dataAdmissao) {
        this.dataAdmissao = dataAdmissao;
    }

    
    @Column(name="nome_pai", length=200)
    public String getNomePai() {
        return this.nomePai;
    }
    
    public void setNomePai(String nomePai) {
        this.nomePai = nomePai;
    }

    
    @Column(name="nome_mae", length=200)
    public String getNomeMae() {
        return this.nomeMae;
    }
    
    public void setNomeMae(String nomeMae) {
        this.nomeMae = nomeMae;
    }

    
    @Column(name="pis", length=45)
    public String getPis() {
        return this.pis;
    }
    
    public void setPis(String pis) {
        this.pis = pis;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_emissao_pis", length=22)
    public Date getDataEmissaoPis() {
        return this.dataEmissaoPis;
    }
    
    public void setDataEmissaoPis(Date dataEmissaoPis) {
        this.dataEmissaoPis = dataEmissaoPis;
    }

    
    @Column(name="reservista", length=45)
    public String getReservista() {
        return this.reservista;
    }
    
    public void setReservista(String reservista) {
        this.reservista = reservista;
    }

    
    @Column(name="categoria_reservista", length=45)
    public String getCategoriaReservista() {
        return this.categoriaReservista;
    }
    
    public void setCategoriaReservista(String categoriaReservista) {
        this.categoriaReservista = categoriaReservista;
    }

    
    @Column(name="nacionalidade", length=100)
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }

    
    @Column(name="naturalidade", length=100)
    public String getNaturalidade() {
        return this.naturalidade;
    }
    
    public void setNaturalidade(String naturalidade) {
        this.naturalidade = naturalidade;
    }

    
    @Column(name="seguro_desemprego", length=1)
    public Character getSeguroDesemprego() {
        return this.seguroDesemprego;
    }
    
    public void setSeguroDesemprego(Character seguroDesemprego) {
        this.seguroDesemprego = seguroDesemprego;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_demissao", length=22)
    public Date getDataDemissao() {
        return this.dataDemissao;
    }
    
    public void setDataDemissao(Date dataDemissao) {
        this.dataDemissao = dataDemissao;
    }

    
    @Column(name="numero_carteira_trabalho", length=45)
    public String getNumeroCarteiraTrabalho() {
        return this.numeroCarteiraTrabalho;
    }
    
    public void setNumeroCarteiraTrabalho(String numeroCarteiraTrabalho) {
        this.numeroCarteiraTrabalho = numeroCarteiraTrabalho;
    }

    
    @Column(name="serie_carteira_trabalho", length=45)
    public String getSerieCarteiraTrabalho() {
        return this.serieCarteiraTrabalho;
    }
    
    public void setSerieCarteiraTrabalho(String serieCarteiraTrabalho) {
        this.serieCarteiraTrabalho = serieCarteiraTrabalho;
    }

    
    @Column(name="estado_carteira_trabalho", length=45)
    public String getEstadoCarteiraTrabalho() {
        return this.estadoCarteiraTrabalho;
    }
    
    public void setEstadoCarteiraTrabalho(String estadoCarteiraTrabalho) {
        this.estadoCarteiraTrabalho = estadoCarteiraTrabalho;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_emissao_carteira_trabalho", length=22)
    public Date getDataEmissaoCarteiraTrabalho() {
        return this.dataEmissaoCarteiraTrabalho;
    }
    
    public void setDataEmissaoCarteiraTrabalho(Date dataEmissaoCarteiraTrabalho) {
        this.dataEmissaoCarteiraTrabalho = dataEmissaoCarteiraTrabalho;
    }

    
    @Column(name="cnh", length=45)
    public String getCnh() {
        return this.cnh;
    }
    
    public void setCnh(String cnh) {
        this.cnh = cnh;
    }

    
    @Column(name="categoria_cnh", length=45)
    public String getCategoriaCnh() {
        return this.categoriaCnh;
    }
    
    public void setCategoriaCnh(String categoriaCnh) {
        this.categoriaCnh = categoriaCnh;
    }

    
    @Column(name="orgao_emissor_cnh", length=45)
    public String getOrgaoEmissorCnh() {
        return this.orgaoEmissorCnh;
    }
    
    public void setOrgaoEmissorCnh(String orgaoEmissorCnh) {
        this.orgaoEmissorCnh = orgaoEmissorCnh;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_emissao_cnh", length=22)
    public Date getDataEmissaoCnh() {
        return this.dataEmissaoCnh;
    }
    
    public void setDataEmissaoCnh(Date dataEmissaoCnh) {
        this.dataEmissaoCnh = dataEmissaoCnh;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_primeira_cnh", length=22)
    public Date getDataPrimeiraCnh() {
        return this.dataPrimeiraCnh;
    }
    
    public void setDataPrimeiraCnh(Date dataPrimeiraCnh) {
        this.dataPrimeiraCnh = dataPrimeiraCnh;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_validade_cnh", length=22)
    public Date getDataValidadeCnh() {
        return this.dataValidadeCnh;
    }
    
    public void setDataValidadeCnh(Date dataValidadeCnh) {
        this.dataValidadeCnh = dataValidadeCnh;
    }

    
    @Column(name="titulo_eleitor", length=45)
    public String getTituloEleitor() {
        return this.tituloEleitor;
    }
    
    public void setTituloEleitor(String tituloEleitor) {
        this.tituloEleitor = tituloEleitor;
    }

    
    @Column(name="zona_titulo_eleitor", length=45)
    public String getZonaTituloEleitor() {
        return this.zonaTituloEleitor;
    }
    
    public void setZonaTituloEleitor(String zonaTituloEleitor) {
        this.zonaTituloEleitor = zonaTituloEleitor;
    }

    
    @Column(name="secao_titulo_eleitor", length=45)
    public String getSecaoTituloEleitor() {
        return this.secaoTituloEleitor;
    }
    
    public void setSecaoTituloEleitor(String secaoTituloEleitor) {
        this.secaoTituloEleitor = secaoTituloEleitor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionarios")
    public Set<EveFixos> getEveFixoses() {
        return this.eveFixoses;
    }
    
    public void setEveFixoses(Set<EveFixos> eveFixoses) {
        this.eveFixoses = eveFixoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionarios")
    public Set<Calculos> getCalculoses() {
        return this.calculoses;
    }
    
    public void setCalculoses(Set<Calculos> calculoses) {
        this.calculoses = calculoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionarios")
    public Set<Dependentes> getDependenteses() {
        return this.dependenteses;
    }
    
    public void setDependenteses(Set<Dependentes> dependenteses) {
        this.dependenteses = dependenteses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionarios")
    public Set<Atestados> getAtestadoses() {
        return this.atestadoses;
    }
    
    public void setAtestadoses(Set<Atestados> atestadoses) {
        this.atestadoses = atestadoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionarios")
    public Set<Salarios> getSalarioses() {
        return this.salarioses;
    }
    
    public void setSalarioses(Set<Salarios> salarioses) {
        this.salarioses = salarioses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionarios")
    public Set<FuncionariosCargos> getFuncionariosCargoses() {
        return this.funcionariosCargoses;
    }
    
    public void setFuncionariosCargoses(Set<FuncionariosCargos> funcionariosCargoses) {
        this.funcionariosCargoses = funcionariosCargoses;
    }




}


