package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FuncionariosCargosId generated by hbm2java
 */
@Embeddable
public class FuncionariosCargosId  implements java.io.Serializable {


     private int cargosId;
     private int funcionariosId;

    public FuncionariosCargosId() {
    }

    public FuncionariosCargosId(int cargosId, int funcionariosId) {
       this.cargosId = cargosId;
       this.funcionariosId = funcionariosId;
    }
   


    @Column(name="cargos_id", nullable=false)
    public int getCargosId() {
        return this.cargosId;
    }
    
    public void setCargosId(int cargosId) {
        this.cargosId = cargosId;
    }


    @Column(name="funcionarios_id", nullable=false)
    public int getFuncionariosId() {
        return this.funcionariosId;
    }
    
    public void setFuncionariosId(int funcionariosId) {
        this.funcionariosId = funcionariosId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FuncionariosCargosId) ) return false;
		 FuncionariosCargosId castOther = ( FuncionariosCargosId ) other; 
         
		 return (this.getCargosId()==castOther.getCargosId())
 && (this.getFuncionariosId()==castOther.getFuncionariosId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCargosId();
         result = 37 * result + this.getFuncionariosId();
         return result;
   }   


}


