package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GrupoEventos generated by hbm2java
 */
@Entity
@Table(name="grupo_eventos"
    ,schema="public"
)
@SequenceGenerator(name = "grupoeventos_seq", sequenceName = "grupoeventos_seq", allocationSize = 1)
public class GrupoEventos  implements java.io.Serializable {


     private int id;
     private String descricao;
     private String observacoes;
     private Set<Eventos> eventoses = new HashSet<Eventos>(0);

    public GrupoEventos() {
    }

	
    public GrupoEventos(int id) {
        this.id = id;
    }
    public GrupoEventos(int id, String descricao, String observacoes, Set<Eventos> eventoses) {
       this.id = id;
       this.descricao = descricao;
       this.observacoes = observacoes;
       this.eventoses = eventoses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grupoeventos_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descricao", length=200)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="observacoes", length=500)
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoEventos")
    public Set<Eventos> getEventoses() {
        return this.eventoses;
    }
    
    public void setEventoses(Set<Eventos> eventoses) {
        this.eventoses = eventoses;
    }




}


