package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Habilidades generated by hbm2java
 */
@Entity
@Table(name="habilidades"
    ,schema="public"
)
@SequenceGenerator(name = "habilidades_seq", sequenceName = "habilidades_seq", allocationSize = 1)
public class Habilidades  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set<Curriculos> curriculoses = new HashSet<Curriculos>(0);
     private Set<Vagas> vagases = new HashSet<Vagas>(0);

    public Habilidades() {
    }

	
    public Habilidades(int id) {
        this.id = id;
    }
    public Habilidades(int id, String descricao, Set<Curriculos> curriculoses, Set<Vagas> vagases) {
       this.id = id;
       this.descricao = descricao;
       this.curriculoses = curriculoses;
       this.vagases = vagases;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "habilidades_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descricao", length=300)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="habilidades_curriculos", schema="public", joinColumns = { 
        @JoinColumn(name="habilidades_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="curriculos_id", nullable=false, updatable=false) })
    public Set<Curriculos> getCurriculoses() {
        return this.curriculoses;
    }
    
    public void setCurriculoses(Set<Curriculos> curriculoses) {
        this.curriculoses = curriculoses;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="habilidades_vagas", schema="public", joinColumns = { 
        @JoinColumn(name="habilidades_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="vagas_id", nullable=false, updatable=false) })
    public Set<Vagas> getVagases() {
        return this.vagases;
    }
    
    public void setVagases(Set<Vagas> vagases) {
        this.vagases = vagases;
    }




}


