package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Setores generated by hbm2java
 */
@Entity
@Table(name="setores"
    ,schema="public"
)
@SequenceGenerator(name = "setores_seq", sequenceName = "setores_seq", allocationSize = 1)
public class Setores  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set<Cargos> cargoses = new HashSet<Cargos>(0);

    public Setores() {
    }

	
    public Setores(int id) {
        this.id = id;
    }
    public Setores(int id, String nome, Set<Cargos> cargoses) {
       this.id = id;
       this.nome = nome;
       this.cargoses = cargoses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "setores_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="setores")
    public Set<Cargos> getCargoses() {
        return this.cargoses;
    }
    
    public void setCargoses(Set<Cargos> cargoses) {
        this.cargoses = cargoses;
    }




}


