package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TabIrrf generated by hbm2java
 */
@Entity
@Table(name="tab_irrf"
    ,schema="public"
)
@SequenceGenerator(name = "tabirrf_seq", sequenceName = "tabirrf_seq", allocationSize = 1)
public class TabIrrf  implements java.io.Serializable {


     private int id;
     private Double valInicial;
     private Double valFinal;
     private Double percentual;
     private Double deducao;
     private Date perInicial;
     private Date perFinal;

    public TabIrrf() {
    }

	
    public TabIrrf(int id) {
        this.id = id;
    }
    public TabIrrf(int id, Double valInicial, Double valFinal, Double percentual, Double deducao, Date perInicial, Date perFinal) {
       this.id = id;
       this.valInicial = valInicial;
       this.valFinal = valFinal;
       this.percentual = percentual;
       this.deducao = deducao;
       this.perInicial = perInicial;
       this.perFinal = perFinal;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tabirrf_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="val_inicial", precision=17, scale=17)
    public Double getValInicial() {
        return this.valInicial;
    }
    
    public void setValInicial(Double valInicial) {
        this.valInicial = valInicial;
    }

    
    @Column(name="val_final", precision=17, scale=17)
    public Double getValFinal() {
        return this.valFinal;
    }
    
    public void setValFinal(Double valFinal) {
        this.valFinal = valFinal;
    }

    
    @Column(name="percentual", precision=17, scale=17)
    public Double getPercentual() {
        return this.percentual;
    }
    
    public void setPercentual(Double percentual) {
        this.percentual = percentual;
    }

    
    @Column(name="deducao", precision=17, scale=17)
    public Double getDeducao() {
        return this.deducao;
    }
    
    public void setDeducao(Double deducao) {
        this.deducao = deducao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="per_inicial", length=13)
    public Date getPerInicial() {
        return this.perInicial;
    }
    
    public void setPerInicial(Date perInicial) {
        this.perInicial = perInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="per_final", length=13)
    public Date getPerFinal() {
        return this.perFinal;
    }
    
    public void setPerFinal(Date perFinal) {
        this.perFinal = perFinal;
    }




}


