package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 21:02:31 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TabSalFamilia generated by hbm2java
 */
@Entity
@Table(name = "tab_sal_familia", schema = "public")
@SequenceGenerator(name = "tabsalfamilia_seq", sequenceName = "tabsalfamilia_seq", allocationSize = 1)
public class TabSalFamilia implements java.io.Serializable {

    private int id;
    private Double valInicial;
    private Double valFinal;
    private Double valor;
    private Date perInicial;
    private Date perFinal;

    public TabSalFamilia() {
    }

    public TabSalFamilia(int id) {
        this.id = id;
    }

    public TabSalFamilia(int id, Double valInicial, Double valFinal, Double valor, Date perInicial, Date perFinal) {
        this.id = id;
        this.valInicial = valInicial;
        this.valFinal = valFinal;
        this.valor = valor;
        this.perInicial = perInicial;
        this.perFinal = perFinal;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tabsalfamilia_seq")
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "val_inicial", precision = 17, scale = 17)
    public Double getValInicial() {
        return this.valInicial;
    }

    public void setValInicial(Double valInicial) {
        this.valInicial = valInicial;
    }

    @Column(name = "val_final", precision = 17, scale = 17)
    public Double getValFinal() {
        return this.valFinal;
    }

    public void setValFinal(Double valFinal) {
        this.valFinal = valFinal;
    }

    @Column(name = "valor", precision = 17, scale = 17)
    public Double getValor() {
        return this.valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "per_inicial", length = 22)
    public Date getPerInicial() {
        return this.perInicial;
    }

    public void setPerInicial(Date perInicial) {
        this.perInicial = perInicial;
    }

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "per_final", length = 22)
    public Date getPerFinal() {
        return this.perFinal;
    }

    public void setPerFinal(Date perFinal) {
        this.perFinal = perFinal;
    }

}
