package com.mirror.alogeda.commons.model;
// Generated 12/05/2018 15:54:17 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,schema="public"
)
@SequenceGenerator(name = "usuarios_seq", sequenceName = "usuarios_seq", allocationSize = 1)
public class Usuarios  implements java.io.Serializable {


     private int id;
     private String nomeUsuario;
     private String senha;
     private boolean senhaInspirada;

    public Usuarios() {
    }

	
    public Usuarios(int id, boolean senhaInspirada) {
        this.id = id;
        this.senhaInspirada = senhaInspirada;
    }
    public Usuarios(int id, String nomeUsuario, String senha, boolean senhaInspirada) {
       this.id = id;
       this.nomeUsuario = nomeUsuario;
       this.senha = senha;
       this.senhaInspirada = senhaInspirada;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "usuarios_seq")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome_usuario", unique=true)
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    
    @Column(name="senha")
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="senha_inspirada", nullable=false)
    public boolean isSenhaInspirada() {
        return this.senhaInspirada;
    }
    
    public void setSenhaInspirada(boolean senhaInspirada) {
        this.senhaInspirada = senhaInspirada;
    }

}


